# Generated by Django 6.1.1 on 2026-09-23 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='version',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_expires_at',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='external_regulation',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='number',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='review_due',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='qualitydirection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='test',
            name='attempts_allowed',
        ),
        migrations.AddField(
            model_name='course',
            name='legacy_passing_score',
            field=models.PositiveSmallIntegerField(db_column='passing_score', default=80, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='legacy_archived',
            field=models.BooleanField(db_column='archived', default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='legacy_version',
            field=models.CharField(db_column='version', default='1.0', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='qualitydirection',
            name='internal_category',
            field=models.CharField(db_column='section', default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='qualitydirection',
            name='internal_code',
            field=models.CharField(db_column='number', default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='qualitydirection',
            name='legacy_reference',
            field=models.TextField(db_column='external_regulation', default='', editable=False),
        ),
        migrations.AddField(
            model_name='qualitydirection',
            name='legacy_status',
            field=models.CharField(db_column='status', default='READY', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='legacy_attempts_allowed',
            field=models.PositiveSmallIntegerField(db_column='attempts_allowed', default=3, editable=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый просмотр'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Назначено'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(verbose_name='Срок прохождения'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Назначено'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Пройдено'), ('OVERDUE', 'Просрочено'), ('FAILED', 'Не пройдено')], default='ASSIGNED', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='Отдел / отделение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, upload_to='lessons/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('DOC', 'Документ'), ('VIDEO', 'YouTube-видео'), ('LINK', 'Внешняя ссылка')], default='DOC', max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Отдел / отделение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('METHODIST', 'Методист'), ('HEAD', 'Руководитель отдела'), ('EMPLOYEE', 'Сотрудник')], default='EMPLOYEE', max_length=12, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='qualitydirection',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='qualitydirection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='qualitydirection',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер верного варианта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер попытки'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='passed',
            field=models.BooleanField(verbose_name='Пройден'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка, %'),
        ),
    ]
