# Generated by Django 6.1.1 on 2026-09-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lesson_options_alter_testattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='demo_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демонстрационные данные'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_indexes',
            field=models.JSONField(blank=True, default=list, verbose_name='Верные варианты'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Пояснение'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Один правильный ответ'), ('MULTIPLE', 'Несколько правильных ответов'), ('TRUE_FALSE', 'Верно / неверно')], default='SINGLE', max_length=12, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Текущая версия'),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован')], default='DRAFT', max_length=12, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='answers_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Снимок ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.course'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('course', 'version')},
        ),
        migrations.CreateModel(
            name='QualityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер требования')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('owner', models.CharField(blank=True, max_length=255, verbose_name='Владелец процесса')),
                ('curator', models.CharField(blank=True, max_length=255, verbose_name='Куратор')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='Необходимые доказательства')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.qualitydirection')),
            ],
            options={
                'ordering': ['number', 'id'],
                'unique_together': {('direction', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='Номер документа')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='Версия')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('review_due', models.DateField(blank=True, null=True, verbose_name='Следующий пересмотр')),
                ('owner', models.CharField(blank=True, max_length=255, verbose_name='Владелец')),
                ('file', models.FileField(upload_to='internal_documents/', verbose_name='PDF')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги')),
                ('status', models.CharField(choices=[('ACTIVE', 'Действует'), ('ARCHIVED', 'Архив')], default='ACTIVE', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='internal_documents', to='core.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_documents', to='core.department')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_documents', to='core.qualitydirection')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.qualityrequirement')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
