# Generated by Django 6.1.1 on 2026-09-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_quality_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldocument',
            name='document_type',
            field=models.CharField(choices=[('SOP', 'СОП'), ('ORDER', 'Приказ'), ('POLICY', 'Положение'), ('FORM', 'Форма / чек-лист'), ('OTHER', 'Другое')], default='OTHER', max_length=10, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='qualityrequirement',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='quality_requirements', to='core.course'),
        ),
    ]
